import { Layout, Columns, Grid, Sparkles, Zap, Palette } from "lucide-react";

export const TEMPLATE_STRUCTURES = {
  classic: {
    name: "Classic",
    description: "Traditional single-column layout with centered content",
    icon: Layout,
    structure: [
      {
        id: "template-hero-classic",
        type: "hero",
        templateId: "hero-1",
        props: {
          heading: "Transform Your Digital Presence",
          subheading: "Create stunning, professional websites in minutes with our intuitive platform. No coding required.",
          ctaText: "Start Building Free",
          ctaLink: "#",
          secondaryCtaText: "Watch Demo",
          secondaryCtaLink: "#demo",
          alignment: "center",
          image: "",
        },
        style: {
          padding: { top: "8rem", bottom: "8rem" },
          backgroundType: "gradient",
          backgroundGradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
        },
      },
      {
        id: "template-features-classic",
        type: "features",
        templateId: "features-grid",
        props: {
          heading: "Everything You Need to Succeed",
          subheading: "Powerful features designed to help you build better websites faster",
          features: [
            {
              id: "f1",
              icon: "zap",
              title: "Lightning Fast",
              description: "Optimized for speed with sub-second load times and instant previews",
            },
            {
              id: "f2",
              icon: "shield",
              title: "Bank-Level Security",
              description: "Enterprise-grade encryption and SSL certificates included",
            },
            {
              id: "f3",
              icon: "smartphone",
              title: "Mobile First",
              description: "Perfectly responsive on every device from phones to desktops",
            },
            {
              id: "f4",
              icon: "globe",
              title: "Global CDN",
              description: "Lightning-fast delivery worldwide with our global network",
            },
            {
              id: "f5",
              icon: "code",
              title: "Custom Code",
              description: "Add your own HTML, CSS, and JavaScript when you need it",
            },
            {
              id: "f6",
              icon: "trending-up",
              title: "SEO Optimized",
              description: "Built-in SEO tools to help you rank higher in search results",
            },
          ],
          columns: 3,
        },
        style: {
          padding: { top: "5rem", bottom: "5rem" },
          backgroundType: "color",
          backgroundColor: "#ffffff",
        },
      },
      {
        id: "template-content-classic",
        type: "content",
        templateId: "content-image",
        props: {
          heading: "Built for Creators, Loved by Professionals",
          content: "<p>We believe that everyone deserves access to professional web tools. Our platform combines the simplicity beginners need with the power professionals demand.</p><p>Join over 100,000 creators who have already built amazing websites with our platform. From portfolios to online stores, landing pages to complete business sites - we've got you covered.</p>",
          image: "",
          imagePosition: "right",
        },
        style: {
          padding: { top: "5rem", bottom: "5rem" },
          backgroundType: "color",
          backgroundColor: "#f9fafb",
        },
      },
      {
        id: "template-testimonials-classic",
        type: "testimonials",
        templateId: "testimonials-grid",
        props: {
          heading: "Trusted by Thousands",
          subheading: "See what our users have to say about their experience",
          testimonials: [
            {
              id: "t1",
              name: "Sarah Mitchell",
              role: "Creative Director, DesignCo",
              content: "This platform completely changed how we approach client projects. The speed and flexibility are unmatched.",
              avatar: "",
              rating: 5,
            },
            {
              id: "t2",
              name: "James Chen",
              role: "Founder, TechStart",
              content: "Finally, a website builder that doesn't limit my creativity. I can build exactly what I envision.",
              avatar: "",
              rating: 5,
            },
            {
              id: "t3",
              name: "Emily Rodriguez",
              role: "Marketing Manager",
              content: "The ROI has been incredible. We launched our site in days, not months, and conversion rates doubled.",
              avatar: "",
              rating: 5,
            },
          ],
        },
        style: {
          padding: { top: "5rem", bottom: "5rem" },
          backgroundType: "color",
          backgroundColor: "#ffffff",
        },
      },
      {
        id: "template-cta-classic",
        type: "cta",
        templateId: "cta-simple",
        props: {
          heading: "Ready to Build Something Amazing?",
          subheading: "Join thousands of creators and start building your dream website today. No credit card required.",
          primaryButton: {
            text: "Get Started Free",
            link: "#",
          },
          secondaryButton: {
            text: "Schedule Demo",
            link: "#",
          },
        },
        style: {
          padding: { top: "7rem", bottom: "7rem" },
          backgroundType: "gradient",
          backgroundGradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
        },
      },
    ],
  },
  modern: {
    name: "Modern",
    description: "Asymmetric layout with bold designs and dynamic elements",
    icon: Columns,
    structure: [
      {
        id: "template-hero-modern",
        type: "hero",
        templateId: "hero-2",
        props: {
          heading: "Design Without Limits",
          subheading: "The future of web design is here. Build stunning, interactive websites that captivate your audience and drive results.",
          ctaText: "Start Your Free Trial",
          ctaLink: "#",
          secondaryCtaText: "Explore Features",
          secondaryCtaLink: "#features",
          image: "",
          alignment: "left",
        },
        style: {
          padding: { top: "9rem", bottom: "9rem" },
          backgroundType: "gradient",
          backgroundGradient: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
        },
      },
      {
        id: "template-stats-modern",
        type: "stats",
        templateId: "stats-row",
        props: {
          stats: [
            {
              id: "s1",
              value: "100K+",
              label: "Active Users",
              description: "Creators worldwide",
            },
            {
              id: "s2",
              value: "99.9%",
              label: "Uptime",
              description: "Guaranteed reliability",
            },
            {
              id: "s3",
              value: "4.9/5",
              label: "Rating",
              description: "From 10K+ reviews",
            },
            {
              id: "s4",
              value: "24/7",
              label: "Support",
              description: "Always here to help",
            },
          ],
        },
        style: {
          padding: { top: "4rem", bottom: "4rem" },
          backgroundType: "color",
          backgroundColor: "#ffffff",
        },
      },
      {
        id: "template-features-modern",
        type: "features",
        templateId: "features-alternating",
        props: {
          heading: "Features That Set Us Apart",
          subheading: "Everything you need to create, launch, and grow your online presence",
          features: [
            {
              id: "f1",
              icon: "layers",
              title: "Drag & Drop Builder",
              description: "Intuitive visual editor that makes building websites as easy as moving blocks around. No technical skills required.",
              image: "",
            },
            {
              id: "f2",
              icon: "palette",
              title: "Unlimited Customization",
              description: "Complete control over every design element. From colors and fonts to layouts and animations - make it yours.",
              image: "",
            },
            {
              id: "f3",
              icon: "rocket",
              title: "One-Click Publishing",
              description: "Go live instantly with a single click. Connect your domain, choose a plan, and you're ready to launch.",
              image: "",
            },
          ],
        },
        style: {
          padding: { top: "6rem", bottom: "6rem" },
          backgroundType: "color",
          backgroundColor: "#f8fafc",
        },
      },
      {
        id: "template-pricing-modern",
        type: "pricing",
        templateId: "pricing-table",
        props: {
          heading: "Choose Your Plan",
          subheading: "Flexible pricing that grows with your business. Cancel anytime.",
          plans: [
            {
              id: "p1",
              name: "Starter",
              price: "$12",
              period: "month",
              description: "Perfect for personal projects",
              features: [
                "5 Website Projects",
                "10GB Storage",
                "Basic Templates",
                "Email Support",
                "Custom Domain",
              ],
              ctaText: "Start Free Trial",
              ctaLink: "#",
              highlighted: false,
            },
            {
              id: "p2",
              name: "Professional",
              price: "$39",
              period: "month",
              description: "For serious creators and businesses",
              features: [
                "Unlimited Projects",
                "100GB Storage",
                "Premium Templates",
                "Priority Support",
                "Advanced SEO Tools",
                "Custom Code",
                "Team Collaboration",
                "Analytics Dashboard",
              ],
              ctaText: "Start Free Trial",
              ctaLink: "#",
              highlighted: true,
              badge: "Most Popular",
            },
            {
              id: "p3",
              name: "Enterprise",
              price: "Custom",
              period: "",
              description: "For large teams and agencies",
              features: [
                "Everything in Pro",
                "Unlimited Storage",
                "White Label Options",
                "Dedicated Account Manager",
                "Custom Integrations",
                "SLA Guarantee",
                "Advanced Security",
                "API Access",
              ],
              ctaText: "Contact Sales",
              ctaLink: "#",
              highlighted: false,
            },
          ],
        },
        style: {
          padding: { top: "6rem", bottom: "6rem" },
          backgroundType: "color",
          backgroundColor: "#ffffff",
        },
      },
      {
        id: "template-faq-modern",
        type: "faq",
        templateId: "faq-accordion",
        props: {
          heading: "Frequently Asked Questions",
          subheading: "Everything you need to know about our platform",
          faqs: [
            {
              id: "faq1",
              question: "Do I need coding knowledge to use this platform?",
              answer: "Not at all! Our platform is designed for everyone, from complete beginners to experienced developers. The visual editor makes it easy to create professional websites without writing a single line of code.",
            },
            {
              id: "faq2",
              question: "Can I use my own domain name?",
              answer: "Yes! You can connect any domain you own or purchase a new one directly through our platform. We'll handle all the technical setup for you.",
            },
            {
              id: "faq3",
              question: "What kind of websites can I build?",
              answer: "Anything you can imagine! From portfolios and blogs to online stores and business websites. Our platform is flexible enough to support any type of website you want to create.",
            },
            {
              id: "faq4",
              question: "Is there a free trial?",
              answer: "Yes! We offer a 14-day free trial on all paid plans. No credit card required. You can explore all features and build your website risk-free.",
            },
          ],
        },
        style: {
          padding: { top: "6rem", bottom: "6rem" },
          backgroundType: "color",
          backgroundColor: "#f8fafc",
        },
      },
      {
        id: "template-cta-modern",
        type: "cta",
        templateId: "cta-split",
        props: {
          heading: "Start Building Today",
          subheading: "Join the community of creators building the future of the web",
          primaryButton: {
            text: "Get Started Free",
            link: "#",
          },
          secondaryButton: {
            text: "Talk to Sales",
            link: "#",
          },
          features: [
            "No credit card required",
            "14-day free trial",
            "Cancel anytime",
          ],
        },
        style: {
          padding: { top: "7rem", bottom: "7rem" },
          backgroundType: "gradient",
          backgroundGradient: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
        },
      },
    ],
  },
  minimal: {
    name: "Minimal",
    description: "Clean, spacious layout with focus on content and clarity",
    icon: Grid,
    structure: [
      {
        id: "template-hero-minimal",
        type: "hero",
        templateId: "hero-1",
        props: {
          heading: "Less Noise. More Impact.",
          subheading: "A refined approach to web design. Clean interfaces, powerful features, and uncompromising simplicity.",
          ctaText: "Get Started",
          ctaLink: "#",
          alignment: "center",
          image: "",
        },
        style: {
          padding: { top: "12rem", bottom: "12rem" },
          backgroundType: "color",
          backgroundColor: "#ffffff",
        },
      },
      {
        id: "template-content-minimal",
        type: "content",
        templateId: "content-text",
        props: {
          heading: "Design Philosophy",
          content: "<p>We believe in the power of restraint. Every pixel, every interaction, every element serves a purpose. Nothing more, nothing less.</p><p>Our platform embodies this philosophy - giving you powerful tools wrapped in an interface so clean and intuitive, it disappears. Letting your content take center stage.</p><p>Because great design isn't about adding more. It's about having the courage to take away everything that isn't essential.</p>",
          alignment: "center",
        },
        style: {
          padding: { top: "8rem", bottom: "8rem" },
          backgroundType: "color",
          backgroundColor: "#fafafa",
        },
      },
      {
        id: "template-features-minimal",
        type: "features",
        templateId: "features-grid",
        props: {
          heading: "Core Principles",
          subheading: "The foundations of our design system",
          features: [
            {
              id: "f1",
              icon: "circle",
              title: "Clarity",
              description: "Clear communication through thoughtful hierarchy and whitespace",
            },
            {
              id: "f2",
              icon: "target",
              title: "Purpose",
              description: "Every element exists for a reason, nothing is arbitrary",
            },
            {
              id: "f3",
              icon: "feather",
              title: "Simplicity",
              description: "Complexity removed, essence preserved, beauty revealed",
            },
            {
              id: "f4",
              icon: "zap",
              title: "Performance",
              description: "Fast, efficient, and optimized for the best experience",
            },
          ],
          columns: 4,
        },
        style: {
          padding: { top: "8rem", bottom: "8rem" },
          backgroundType: "color",
          backgroundColor: "#ffffff",
        },
      },
      {
        id: "template-process-minimal",
        type: "process",
        templateId: "process-timeline",
        props: {
          heading: "How It Works",
          subheading: "Three simple steps to your perfect website",
          steps: [
            {
              id: "step1",
              number: "01",
              title: "Choose",
              description: "Select a template that matches your vision. Or start from scratch.",
            },
            {
              id: "step2",
              number: "02",
              title: "Customize",
              description: "Make it yours with our intuitive visual editor. No limits.",
            },
            {
              id: "step3",
              number: "03",
              title: "Launch",
              description: "Publish with a single click. Share your creation with the world.",
            },
          ],
        },
        style: {
          padding: { top: "8rem", bottom: "8rem" },
          backgroundType: "color",
          backgroundColor: "#fafafa",
        },
      },
      {
        id: "template-testimonials-minimal",
        type: "testimonials",
        templateId: "testimonials-minimal",
        props: {
          heading: "What People Say",
          testimonials: [
            {
              id: "t1",
              content: "The most elegant web builder I've ever used. It stays out of the way and lets me focus on what matters - the content.",
              name: "Alex Morgan",
              role: "Product Designer",
            },
            {
              id: "t2",
              content: "Finally, a platform that respects my time and intelligence. No clutter, no distractions, just pure functionality.",
              name: "Jordan Lee",
              role: "Entrepreneur",
            },
          ],
        },
        style: {
          padding: { top: "8rem", bottom: "8rem" },
          backgroundType: "color",
          backgroundColor: "#ffffff",
        },
      },
      {
        id: "template-contact-minimal",
        type: "contact",
        templateId: "contact-form",
        props: {
          heading: "Let's Talk",
          subheading: "Have a question? We'd love to hear from you.",
          fields: [
            { id: "name", type: "text", label: "Name", required: true },
            { id: "email", type: "email", label: "Email", required: true },
            { id: "message", type: "textarea", label: "Message", required: true },
          ],
          submitText: "Send Message",
        },
        style: {
          padding: { top: "8rem", bottom: "8rem" },
          backgroundType: "color",
          backgroundColor: "#fafafa",
        },
      },
      {
        id: "template-cta-minimal",
        type: "cta",
        templateId: "cta-simple",
        props: {
          heading: "Ready?",
          subheading: "Start building your minimalist website today",
          primaryButton: {
            text: "Begin",
            link: "#",
          },
          secondaryButton: {
            text: "Learn More",
            link: "#",
          },
        },
        style: {
          padding: { top: "10rem", bottom: "10rem" },
          backgroundType: "color",
          backgroundColor: "#000000",
        },
      },
    ],
  },
  bold: {
    name: "Bold",
    description: "Vibrant colors and large typography for maximum impact",
    icon: Sparkles,
    structure: [
      {
        id: "template-hero-bold",
        type: "hero",
        templateId: "hero-2",
        props: {
          heading: "Make an Unforgettable First Impression",
          subheading: "Bold design. Powerful features. Unstoppable results. Your website should be as ambitious as you are.",
          ctaText: "Launch Your Site",
          ctaLink: "#",
          secondaryCtaText: "See Examples",
          secondaryCtaLink: "#examples",
          alignment: "center",
          image: "",
        },
        style: {
          padding: { top: "10rem", bottom: "10rem" },
          backgroundType: "gradient",
          backgroundGradient: "linear-gradient(135deg, #fa709a 0%, #fee140 100%)",
        },
      },
      {
        id: "template-value-bold",
        type: "content",
        templateId: "content-split",
        props: {
          heading: "Stand Out or Fade Away",
          content: "<p>In a world of bland, cookie-cutter websites, yours should stop people in their tracks. Our platform gives you the creative freedom to build something truly remarkable.</p><p>Vibrant colors. Dynamic animations. Bold typography. Everything you need to create a website that demands attention and converts visitors into customers.</p>",
          image: "",
          imagePosition: "left",
        },
        style: {
          padding: { top: "6rem", bottom: "6rem" },
          backgroundType: "color",
          backgroundColor: "#ffffff",
        },
      },
      {
        id: "template-features-bold",
        type: "features",
        templateId: "features-cards",
        props: {
          heading: "Powerful Features for Bold Creators",
          subheading: "Tools that match your ambition",
          features: [
            {
              id: "f1",
              icon: "palette",
              title: "Unlimited Colors",
              description: "Full control over every color in your design. Create vibrant gradients and eye-catching combinations.",
              color: "#ff6b6b",
            },
            {
              id: "f2",
              icon: "type",
              title: "Dynamic Typography",
              description: "Choose from hundreds of fonts or upload your own. Make your text as bold as your vision.",
              color: "#4ecdc4",
            },
            {
              id: "f3",
              icon: "film",
              title: "Smooth Animations",
              description: "Bring your site to life with scroll animations, hover effects, and transitions.",
              color: "#ffe66d",
            },
            {
              id: "f4",
              icon: "image",
              title: "Media Rich",
              description: "Full support for images, videos, GIFs, and background media that captivates.",
              color: "#a8e6cf",
            },
            {
              id: "f5",
              icon: "layout",
              title: "Flexible Layouts",
              description: "Break free from rigid grids. Create asymmetric, overlapping, multi-column designs.",
              color: "#ff8b94",
            },
            {
              id: "f6",
              icon: "smartphone",
              title: "Mobile Perfect",
              description: "Your bold design looks incredible on every device, automatically optimized.",
              color: "#b4a7d6",
            },
          ],
          columns: 3,
        },
        style: {
          padding: { top: "6rem", bottom: "6rem" },
          backgroundType: "color",
          backgroundColor: "#f8f9fa",
        },
      },
      {
        id: "template-social-proof-bold",
        type: "logos",
        templateId: "logo-grid",
        props: {
          heading: "Trusted by Industry Leaders",
          subheading: "Join thousands of bold brands building with us",
          logos: [
            { id: "l1", name: "TechCorp", image: "" },
            { id: "l2", name: "DesignHub", image: "" },
            { id: "l3", name: "StartupXYZ", image: "" },
            { id: "l4", name: "CreativeStudio", image: "" },
            { id: "l5", name: "BrandCo", image: "" },
            { id: "l6", name: "AgencyPro", image: "" },
          ],
        },
        style: {
          padding: { top: "5rem", bottom: "5rem" },
          backgroundType: "color",
          backgroundColor: "#ffffff",
        },
      },
      {
        id: "template-testimonials-bold",
        type: "testimonials",
        templateId: "testimonials-showcase",
        props: {
          heading: "Real Results from Real People",
          testimonials: [
            {
              id: "t1",
              name: "Marcus Rivera",
              role: "Brand Director, CreativeLab",
              content: "This platform unleashed our creativity. We built a website that perfectly captures our brand's energy and personality. Client response has been phenomenal.",
              avatar: "",
              rating: 5,
              metric: "300% increase in engagement",
            },
            {
              id: "t2",
              name: "Sophia Park",
              role: "Founder, BoldStartup",
              content: "Finally, a website builder that doesn't hold you back. We launched a site that turned heads and converted visitors at twice the industry average.",
              avatar: "",
              rating: 5,
              metric: "2x conversion rate",
            },
          ],
        },
        style: {
          padding: { top: "6rem", bottom: "6rem" },
          backgroundType: "gradient",
          backgroundGradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
        },
      },
      {
        id: "template-cta-bold",
        type: "cta",
        templateId: "cta-hero",
        props: {
          heading: "Your Bold Future Starts Now",
          subheading: "Stop settling for ordinary. Build a website that makes a statement.",
          primaryButton: {
            text: "Start Creating Free",
            link: "#",
          },
          secondaryButton: {
            text: "View Showcase",
            link: "#",
          },
          highlightText: "Join 50,000+ creators building bold",
        },
        style: {
          padding: { top: "8rem", bottom: "8rem" },
          backgroundType: "gradient",
          backgroundGradient: "linear-gradient(135deg, #fa709a 0%, #fee140 100%)",
        },
      },
    ],
  },
  creative: {
    name: "Creative",
    description: "Artistic layouts with unique sections and interactive elements",
    icon: Palette,
    structure: [
      {
        id: "template-hero-creative",
        type: "hero",
        templateId: "hero-split",
        props: {
          heading: "Where Creativity Meets Technology",
          subheading: "Express yourself without limits. Build websites that are as unique as your vision.",
          ctaText: "Explore Platform",
          ctaLink: "#",
          image: "",
          alignment: "left",
        },
        style: {
          padding: { top: "8rem", bottom: "8rem" },
          backgroundType: "gradient",
          backgroundGradient: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
        },
      },
      {
        id: "template-gallery-creative",
        type: "gallery",
        templateId: "gallery-masonry",
        props: {
          heading: "Showcase Your Work",
          subheading: "Beautiful galleries that do justice to your creativity",
          items: [
            { id: "g1", image: "", title: "Project Alpha", category: "Design" },
            { id: "g2", image: "", title: "Project Beta", category: "Development" },
            { id: "g3", image: "", title: "Project Gamma", category: "Branding" },
            { id: "g4", image: "", title: "Project Delta", category: "Photography" },
            { id: "g5", image: "", title: "Project Epsilon", category: "Illustration" },
            { id: "g6", image: "", title: "Project Zeta", category: "Animation" },
          ],
          columns: 3,
        },
        style: {
          padding: { top: "6rem", bottom: "6rem" },
          backgroundType: "color",
          backgroundColor: "#ffffff",
        },
      },
      {
        id: "template-features-creative",
        type: "features",
        templateId: "features-creative",
        props: {
          heading: "Tools for Creative Minds",
          features: [
            {
              id: "f1",
              icon: "brush",
              title: "Visual Freedom",
              description: "No templates, no constraints. Start with a blank canvas and create anything you imagine.",
            },
            {
              id: "f2",
              icon: "layers",
              title: "Advanced Layers",
              description: "Layer elements, adjust z-index, create depth and dimension in your designs.",
            },
            {
              id: "f3",
              icon: "wand",
              title: "Smart Effects",
              description: "Parallax scrolling, hover animations, scroll-triggered effects, and more.",
            },
            {
              id: "f4",
              icon: "droplet",
              title: "Color Harmony",
              description: "AI-powered color suggestions that ensure your palette is always on point.",
            },
          ],
        },
        style: {
          padding: { top: "6rem", bottom: "6rem" },
          backgroundType: "color",
          backgroundColor: "#f8fafc",
        },
      },
      {
        id: "template-portfolio-creative",
        type: "content",
        templateId: "content-showcase",
        props: {
          heading: "Built by Creators, for Creators",
          content: "<p>We understand the creative process because we live it. This platform was born from frustration with tools that limit rather than enable.</p><p>Every feature, every interaction, every pixel has been crafted with the creative professional in mind. No compromises, no limitations, just pure creative freedom.</p>",
          showcaseItems: [
            { icon: "award", stat: "500+", label: "Award-winning sites" },
            { icon: "users", stat: "50K+", label: "Creative professionals" },
            { icon: "globe", stat: "180+", label: "Countries worldwide" },
          ],
        },
        style: {
          padding: { top: "6rem", bottom: "6rem" },
          backgroundType: "color",
          backgroundColor: "#ffffff",
        },
      },
      {
        id: "template-team-creative",
        type: "team",
        templateId: "team-creative",
        props: {
          heading: "Meet the Creators",
          subheading: "The talented people behind the platform",
          members: [
            {
              id: "m1",
              name: "Olivia Chen",
              role: "Creative Director",
              bio: "Former lead designer at top agencies",
              image: "",
              socials: { twitter: "#", linkedin: "#", dribbble: "#" },
            },
            {
              id: "m2",
              name: "Marcus Thompson",
              role: "Head of Product",
              bio: "Building tools that empower creators",
              image: "",
              socials: { twitter: "#", linkedin: "#" },
            },
            {
              id: "m3",
              name: "Yuki Tanaka",
              role: "Lead Engineer",
              bio: "Turning creative visions into reality",
              image: "",
              socials: { github: "#", linkedin: "#" },
            },
          ],
        },
        style: {
          padding: { top: "6rem", bottom: "6rem" },
          backgroundType: "color",
          backgroundColor: "#f8fafc",
        },
      },
      {
        id: "template-newsletter-creative",
        type: "newsletter",
        templateId: "newsletter-creative",
        props: {
          heading: "Stay Inspired",
          subheading: "Get creative tips, design trends, and platform updates delivered to your inbox",
          placeholder: "Enter your email",
          buttonText: "Subscribe",
          benefits: [
            "Weekly design inspiration",
            "Exclusive tutorials",
            "Early access to new features",
          ],
        },
        style: {
          padding: { top: "6rem", bottom: "6rem" },
          backgroundType: "gradient",
          backgroundGradient: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)",
        },
      },
      {
        id: "template-cta-creative",
        type: "cta",
        templateId: "cta-creative",
        props: {
          heading: "Create Something Extraordinary",
          subheading: "Your masterpiece awaits. Start building today.",
          primaryButton: {
            text: "Start Free",
            link: "#",
          },
          secondaryButton: {
            text: "View Examples",
            link: "#",
          },
        },
        style: {
          padding: { top: "8rem", bottom: "8rem" },
          backgroundType: "gradient",
          backgroundGradient: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
        },
      },
    ],
  },
  business: {
    name: "Business",
    description: "Professional layout optimized for conversions and credibility",
    icon: Zap,
    structure: [
      {
        id: "template-hero-business",
        type: "hero",
        templateId: "hero-business",
        props: {
          heading: "Grow Your Business Online",
          subheading: "Professional websites that drive results. Built for businesses that mean business.",
          ctaText: "Get Started",
          ctaLink: "#",
          secondaryCtaText: "See Pricing",
          secondaryCtaLink: "#pricing",
          trustBadges: [
            "Trusted by 10,000+ businesses",
            "99.9% uptime guarantee",
            "SOC 2 certified",
          ],
          alignment: "center",
        },
        style: {
          padding: { top: "8rem", bottom: "8rem" },
          backgroundType: "gradient",
          backgroundGradient: "linear-gradient(135deg, #1e3a8a 0%, #3730a3 100%)",
        },
      },
      {
        id: "template-benefits-business",
        type: "benefits",
        templateId: "benefits-grid",
        props: {
          heading: "Why Businesses Choose Us",
          subheading: "Everything you need to establish credibility and drive growth",
          benefits: [
            {
              id: "b1",
              icon: "trending-up",
              title: "Increase Conversions",
              description: "Optimized layouts and CTAs that turn visitors into customers. Average 35% increase in conversion rates.",
            },
            {
              id: "b2",
              icon: "shield-check",
              title: "Build Trust",
              description: "Professional design, security badges, and social proof that establish credibility instantly.",
            },
            {
              id: "b3",
              icon: "clock",
              title: "Save Time",
              description: "Launch in days, not months. Pre-built sections and templates designed for business needs.",
            },
            {
              id: "b4",
              icon: "users",
              title: "Team Collaboration",
              description: "Work together seamlessly. Assign roles, track changes, and streamline your workflow.",
            },
            {
              id: "b5",
              icon: "bar-chart",
              title: "Track Performance",
              description: "Built-in analytics show what's working. Make data-driven decisions to grow faster.",
            },
            {
              id: "b6",
              icon: "headphones",
              title: "Expert Support",
              description: "Dedicated account managers and 24/7 support. We're invested in your success.",
            },
          ],
          columns: 3,
        },
        style: {
          padding: { top: "6rem", bottom: "6rem" },
          backgroundType: "color",
          backgroundColor: "#ffffff",
        },
      },
      {
        id: "template-process-business",
        type: "process",
        templateId: "process-steps",
        props: {
          heading: "Get Online in 3 Simple Steps",
          steps: [
            {
              id: "s1",
              number: "1",
              title: "Choose Your Template",
              description: "Select from industry-specific templates designed to convert. Or customize from scratch.",
            },
            {
              id: "s2",
              number: "2",
              title: "Add Your Content",
              description: "Our AI helps you craft compelling copy. Upload your images and branding in minutes.",
            },
            {
              id: "s3",
              number: "3",
              title: "Launch & Grow",
              description: "Connect your domain, publish, and start growing. We'll handle the technical details.",
            },
          ],
        },
        style: {
          padding: { top: "6rem", bottom: "6rem" },
          backgroundType: "color",
          backgroundColor: "#f8fafc",
        },
      },
      {
        id: "template-case-studies-business",
        type: "case-studies",
        templateId: "case-studies-cards",
        props: {
          heading: "Success Stories",
          subheading: "See how businesses like yours are growing with our platform",
          caseStudies: [
            {
              id: "cs1",
              company: "TechFlow Solutions",
              industry: "SaaS",
              result: "3x increase in qualified leads",
              description: "How TechFlow redesigned their site and tripled their lead generation in 60 days.",
              metrics: { leads: "+300%", traffic: "+150%", conversions: "+85%" },
            },
            {
              id: "cs2",
              company: "GreenLeaf Consulting",
              industry: "Professional Services",
              result: "$500K in new business",
              description: "The website redesign that helped GreenLeaf land their biggest clients yet.",
              metrics: { revenue: "+$500K", clients: "+47", satisfaction: "4.9/5" },
            },
          ],
        },
        style: {
          padding: { top: "6rem", bottom: "6rem" },
          backgroundType: "color",
          backgroundColor: "#ffffff",
        },
      },
      {
        id: "template-pricing-business",
        type: "pricing",
        templateId: "pricing-comparison",
        props: {
          heading: "Transparent Pricing for Every Business",
          subheading: "No hidden fees. No surprises. Just straightforward plans that grow with you.",
          plans: [
            {
              id: "p1",
              name: "Startup",
              price: "$29",
              period: "month",
              description: "Perfect for new businesses",
              features: [
                "1 Website",
                "Custom Domain",
                "SSL Certificate",
                "10GB Storage",
                "Email Support",
                "Basic Analytics",
              ],
              ctaText: "Start Free Trial",
              ctaLink: "#",
              highlighted: false,
            },
            {
              id: "p2",
              name: "Growth",
              price: "$79",
              period: "month",
              description: "For growing businesses",
              features: [
                "5 Websites",
                "Priority Support",
                "50GB Storage",
                "Advanced Analytics",
                "A/B Testing",
                "Team Collaboration",
                "Custom Code",
                "API Access",
              ],
              ctaText: "Start Free Trial",
              ctaLink: "#",
              highlighted: true,
              badge: "Most Popular",
              savings: "Save 20%",
            },
            {
              id: "p3",
              name: "Enterprise",
              price: "Custom",
              period: "",
              description: "For large organizations",
              features: [
                "Unlimited Websites",
                "Dedicated Manager",
                "Unlimited Storage",
                "White Label",
                "Custom SLA",
                "Advanced Security",
                "Multi-region Hosting",
                "Custom Integrations",
              ],
              ctaText: "Contact Sales",
              ctaLink: "#",
              highlighted: false,
            },
          ],
        },
        style: {
          padding: { top: "6rem", bottom: "6rem" },
          backgroundType: "color",
          backgroundColor: "#f8fafc",
        },
      },
      {
        id: "template-trust-business",
        type: "trust",
        templateId: "trust-section",
        props: {
          heading: "Trusted by Industry Leaders",
          stats: [
            { value: "10,000+", label: "Active Businesses" },
            { value: "$50M+", label: "Revenue Generated" },
            { value: "99.9%", label: "Uptime SLA" },
            { value: "24/7", label: "Support Available" },
          ],
          certifications: [
            { name: "SOC 2 Type II", icon: "shield" },
            { name: "GDPR Compliant", icon: "lock" },
            { name: "ISO 27001", icon: "award" },
          ],
        },
        style: {
          padding: { top: "5rem", bottom: "5rem" },
          backgroundType: "color",
          backgroundColor: "#ffffff",
        },
      },
      {
        id: "template-cta-business",
        type: "cta",
        templateId: "cta-business",
        props: {
          heading: "Ready to Grow Your Business?",
          subheading: "Join thousands of businesses building their online presence with us. Start your free 14-day trial today.",
          primaryButton: {
            text: "Start Free Trial",
            link: "#",
          },
          secondaryButton: {
            text: "Schedule Demo",
            link: "#",
          },
          features: [
            "No credit card required",
            "Full platform access",
            "Cancel anytime",
          ],
        },
        style: {
          padding: { top: "8rem", bottom: "8rem" },
          backgroundType: "gradient",
          backgroundGradient: "linear-gradient(135deg, #1e3a8a 0%, #3730a3 100%)",
        },
      },
    ],
  },
};