export const SECTION_TYPES = {
  HERO: "hero",
  FEATURES: "features",
  CTA: "cta",
  CONTENT: "content",
  GALLERY: "gallery",
  TESTIMONIALS: "testimonials",
  PRICING: "pricing",
  CONTACT: "contact",
  TEAM: "team",
  FAQ: "faq",
  STATS: "stats",
  NEWSLETTER: "newsletter",
  PROCESS: "process",
  BENEFITS: "benefits",
  LOGOS: "logos",
};

export const SECTION_LIBRARY = [
  {
    id: "hero-1",
    type: SECTION_TYPES.HERO,
    name: "Hero - Centered",
    icon: "layout",
    defaultProps: {
      heading: "Transform Your Digital Presence",
      subheading: "Build amazing websites in minutes with our intuitive platform",
      ctaText: "Get Started Free",
      ctaLink: "#",
      secondaryCtaText: "Watch Demo",
      secondaryCtaLink: "#demo",
      alignment: "center",
      image: "",
    },
  },
  {
    id: "hero-2",
    type: SECTION_TYPES.HERO,
    name: "Hero - Split",
    icon: "columns",
    defaultProps: {
      heading: "Build Your Dream Website",
      subheading: "Professional tools for modern creators and businesses",
      ctaText: "Start Free Trial",
      ctaLink: "#",
      secondaryCtaText: "Learn More",
      secondaryCtaLink: "#features",
      image: "",
      alignment: "left",
    },
  },
  {
    id: "hero-bold",
    type: SECTION_TYPES.HERO,
    name: "Hero - Bold",
    icon: "sparkles",
    defaultProps: {
      heading: "Make an Impact",
      subheading: "Stand out with bold design and powerful features",
      ctaText: "Get Started",
      ctaLink: "#",
      secondaryCtaText: "See Examples",
      secondaryCtaLink: "#",
      alignment: "center",
      image: "",
    },
  },
  {
    id: "features-grid",
    type: SECTION_TYPES.FEATURES,
    name: "Features - Grid",
    icon: "grid",
    defaultProps: {
      heading: "Everything You Need",
      subheading: "Powerful features to help you succeed",
      features: [
        {
          id: "f1",
          icon: "zap",
          title: "Lightning Fast",
          description: "Optimized for speed with instant load times",
        },
        {
          id: "f2",
          icon: "shield",
          title: "Secure & Safe",
          description: "Enterprise-grade security built-in",
        },
        {
          id: "f3",
          icon: "smartphone",
          title: "Mobile Ready",
          description: "Perfect on every device and screen size",
        },
        {
          id: "f4",
          icon: "globe",
          title: "Global CDN",
          description: "Fast delivery worldwide",
        },
        {
          id: "f5",
          icon: "code",
          title: "Developer Friendly",
          description: "Custom code when you need it",
        },
        {
          id: "f6",
          icon: "trending-up",
          title: "SEO Optimized",
          description: "Rank higher in search results",
        },
      ],
      columns: 3,
    },
  },
  {
    id: "features-list",
    type: SECTION_TYPES.FEATURES,
    name: "Features - List",
    icon: "list",
    defaultProps: {
      heading: "Why Choose Us",
      subheading: "Built for success from day one",
      features: [
        {
          id: "f1",
          icon: "check-circle",
          title: "Easy to Use",
          description: "Intuitive interface designed for everyone",
        },
        {
          id: "f2",
          icon: "check-circle",
          title: "Powerful Tools",
          description: "Advanced features when you need them",
        },
        {
          id: "f3",
          icon: "check-circle",
          title: "Flexible Design",
          description: "Customize every aspect of your site",
        },
      ],
      columns: 2,
    },
  },
  {
    id: "stats-row",
    type: SECTION_TYPES.STATS,
    name: "Stats - Row",
    icon: "bar-chart",
    defaultProps: {
      stats: [
        {
          id: "s1",
          value: "100K+",
          label: "Active Users",
          description: "Worldwide",
        },
        {
          id: "s2",
          value: "99.9%",
          label: "Uptime",
          description: "Guaranteed",
        },
        {
          id: "s3",
          value: "4.9/5",
          label: "Rating",
          description: "Customer satisfaction",
        },
        {
          id: "s4",
          value: "24/7",
          label: "Support",
          description: "Always available",
        },
      ],
    },
  },
  {
    id: "cta-simple",
    type: SECTION_TYPES.CTA,
    name: "Call to Action - Simple",
    icon: "mouse-pointer",
    defaultProps: {
      heading: "Ready to Get Started?",
      subheading: "Join thousands of satisfied customers today",
      primaryButton: {
        text: "Start Free Trial",
        link: "#",
      },
      secondaryButton: {
        text: "Contact Sales",
        link: "#",
      },
    },
  },
  {
    id: "cta-features",
    type: SECTION_TYPES.CTA,
    name: "Call to Action - With Features",
    icon: "zap",
    defaultProps: {
      heading: "Start Building Today",
      subheading: "Everything you need to succeed online",
      primaryButton: {
        text: "Get Started Free",
        link: "#",
      },
      secondaryButton: {
        text: "Learn More",
        link: "#",
      },
      features: [
        "No credit card required",
        "14-day free trial",
        "Cancel anytime",
      ],
    },
  },
  {
    id: "content-text",
    type: SECTION_TYPES.CONTENT,
    name: "Content - Text Only",
    icon: "file-text",
    defaultProps: {
      heading: "Our Story",
      content: "<p>We believe in building tools that empower everyone to create amazing websites. Our platform combines simplicity with powerful features.</p><p>Join thousands of creators who have already transformed their online presence with our platform.</p>",
      alignment: "left",
    },
  },
  {
    id: "content-image",
    type: SECTION_TYPES.CONTENT,
    name: "Content - With Image",
    icon: "image",
    defaultProps: {
      heading: "Built for Creators",
      content: "<p>We believe that everyone deserves access to professional web tools. Our platform combines simplicity with power.</p><p>From portfolios to online stores, we've got you covered with everything you need to succeed online.</p>",
      image: "",
      imagePosition: "right",
    },
  },
  {
    id: "gallery-grid",
    type: SECTION_TYPES.GALLERY,
    name: "Gallery - Grid",
    icon: "grid",
    defaultProps: {
      heading: "Our Work",
      subheading: "Explore our latest projects",
      items: [],
      columns: 3,
    },
  },
  {
    id: "gallery-masonry",
    type: SECTION_TYPES.GALLERY,
    name: "Gallery - Masonry",
    icon: "layout",
    defaultProps: {
      heading: "Portfolio",
      subheading: "Showcasing creative excellence",
      items: [
        { id: "g1", image: "", title: "Project Alpha", category: "Design" },
        { id: "g2", image: "", title: "Project Beta", category: "Development" },
        { id: "g3", image: "", title: "Project Gamma", category: "Branding" },
      ],
      columns: 3,
    },
  },
  {
    id: "testimonials-grid",
    type: SECTION_TYPES.TESTIMONIALS,
    name: "Testimonials - Grid",
    icon: "message-square",
    defaultProps: {
      heading: "What Our Customers Say",
      subheading: "Real feedback from real people",
      testimonials: [
        {
          id: "t1",
          name: "Sarah Mitchell",
          role: "Creative Director",
          content: "This platform transformed how we build websites. The flexibility and ease of use are unmatched.",
          avatar: "",
          rating: 5,
        },
        {
          id: "t2",
          name: "James Chen",
          role: "Startup Founder",
          content: "Finally, a website builder that doesn't limit creativity. Highly recommended!",
          avatar: "",
          rating: 5,
        },
      ],
    },
  },
  {
    id: "testimonials-showcase",
    type: SECTION_TYPES.TESTIMONIALS,
    name: "Testimonials - Showcase",
    icon: "star",
    defaultProps: {
      heading: "Success Stories",
      subheading: "See what our clients have achieved",
      testimonials: [
        {
          id: "t1",
          name: "Emily Rodriguez",
          role: "Marketing Manager",
          content: "The ROI has been incredible. We launched in days and saw immediate results.",
          avatar: "",
          rating: 5,
          metric: "300% increase",
        },
      ],
    },
  },
  {
    id: "pricing-table",
    type: SECTION_TYPES.PRICING,
    name: "Pricing - Table",
    icon: "dollar-sign",
    defaultProps: {
      heading: "Choose Your Plan",
      subheading: "Flexible pricing that grows with you",
      plans: [
        {
          id: "p1",
          name: "Starter",
          price: "$12",
          period: "month",
          description: "Perfect for individuals",
          features: [
            "5 Projects",
            "10GB Storage",
            "Basic Support",
          ],
          ctaText: "Get Started",
          ctaLink: "#",
          highlighted: false,
        },
        {
          id: "p2",
          name: "Pro",
          price: "$39",
          period: "month",
          description: "For professionals",
          features: [
            "Unlimited Projects",
            "100GB Storage",
            "Priority Support",
            "Advanced Features",
          ],
          ctaText: "Start Trial",
          ctaLink: "#",
          highlighted: true,
          badge: "Most Popular",
        },
        {
          id: "p3",
          name: "Enterprise",
          price: "Custom",
          period: "",
          description: "For large teams",
          features: [
            "Everything in Pro",
            "Unlimited Storage",
            "Dedicated Support",
            "Custom Features",
          ],
          ctaText: "Contact Us",
          ctaLink: "#",
          highlighted: false,
        },
      ],
    },
  },
  {
    id: "contact-form",
    type: SECTION_TYPES.CONTACT,
    name: "Contact Form",
    icon: "mail",
    defaultProps: {
      heading: "Get In Touch",
      subheading: "We'd love to hear from you",
      fields: [
        { id: "name", type: "text", label: "Name", required: true },
        { id: "email", type: "email", label: "Email", required: true },
        { id: "message", type: "textarea", label: "Message", required: true },
      ],
      submitText: "Send Message",
    },
  },
  {
    id: "team-grid",
    type: SECTION_TYPES.TEAM,
    name: "Team - Grid",
    icon: "users",
    defaultProps: {
      heading: "Meet Our Team",
      subheading: "The people behind the product",
      members: [
        {
          id: "m1",
          name: "Olivia Chen",
          role: "Creative Director",
          bio: "Leading design with passion and precision",
          image: "",
          socials: {},
        },
        {
          id: "m2",
          name: "Marcus Thompson",
          role: "Head of Product",
          bio: "Building tools that empower creators",
          image: "",
          socials: {},
        },
        {
          id: "m3",
          name: "Yuki Tanaka",
          role: "Lead Engineer",
          bio: "Crafting elegant technical solutions",
          image: "",
          socials: {},
        },
      ],
      columns: 3,
    },
  },
  {
    id: "faq-accordion",
    type: SECTION_TYPES.FAQ,
    name: "FAQ - Accordion",
    icon: "help-circle",
    defaultProps: {
      heading: "Frequently Asked Questions",
      subheading: "Everything you need to know",
      faqs: [
        {
          id: "q1",
          question: "Do I need coding knowledge?",
          answer: "Not at all! Our platform is designed for everyone, from complete beginners to experienced developers.",
        },
        {
          id: "q2",
          question: "Can I use my own domain?",
          answer: "Yes! You can connect any domain you own or purchase a new one directly through our platform.",
        },
        {
          id: "q3",
          question: "What kind of websites can I build?",
          answer: "Anything you can imagine! From portfolios and blogs to online stores and business sites.",
        },
      ],
    },
  },
  {
    id: "newsletter-simple",
    type: SECTION_TYPES.NEWSLETTER,
    name: "Newsletter",
    icon: "mail",
    defaultProps: {
      heading: "Stay Updated",
      subheading: "Get the latest news and updates delivered to your inbox",
      placeholder: "Enter your email",
      buttonText: "Subscribe",
      benefits: [
        "Weekly insights",
        "Exclusive content",
        "Early access",
      ],
    },
  },
];

export const createNewSection = (libraryItem) => {
  return {
    id: `section-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    type: libraryItem.type,
    templateId: libraryItem.id,
    props: JSON.parse(JSON.stringify(libraryItem.defaultProps)),
    style: {
      padding: {
        top: "4rem",
        bottom: "4rem",
      },
      backgroundType: "color",
      backgroundColor: "transparent",
      backgroundGradient: "",
      backgroundImage: "",
      backgroundOverlay: 0,
    },
  };
};